# from osx_development
include_recipe "sprout-osx-base::bash_it"
include_recipe "pivotal_workstation::git_config_global_defaults"
include_recipe "pivotal_workstation::github_for_mac"
include_recipe "sprout-osx-settings::global_environment_variables"
include_recipe "sprout-osx-base::homebrew"
include_recipe "sprout-osx-apps::iterm2"
include_recipe "pivotal_workstation::textmate2"
include_recipe "pivotal_workstation::unix_essentials"
include_recipe "sprout-osx-apps::vagrant"
include_recipe "pivotal_workstation::vim"
include_recipe "pivotal_workstation::vim_config"
include_recipe "sprout-osx-apps::virtualbox"
include_recipe "pivotal_workstation::workspace_directory"
# from ruby_development
include_recipe "pivotal_workstation::rvm"
include_recipe "pivotal_workstation::gem_setup"
include_recipe "pivotal_workstation::mysql"
include_recipe "pivotal_workstation::postgres"
include_recipe "sprout-osx-apps::imagemagick"
include_recipe "sprout-osx-apps::node_js"
include_recipe "pivotal_workstation::qt"
