# from osx_development
include_recipe "sprout-osx-base::bash_it"
include_recipe "pivotal_workstation::git_config_global_defaults"
include_recipe "pivotal_workstation::github_for_mac"
include_recipe "sprout-osx-settings::global_environment_variables"
include_recipe "sprout-osx-base::homebrew"
include_recipe "sprout-osx-apps::iterm2"
include_recipe "pivotal_workstation::textmate2"
include_recipe "pivotal_workstation::unix_essentials"
include_recipe "sprout-osx-apps::vagrant"
include_recipe "pivotal_workstation::vim"
include_recipe "pivotal_workstation::vim_config"
include_recipe "sprout-osx-apps::virtualbox"
# from ruby_development
include_recipe "pivotal_workstation::rvm"
include_recipe "pivotal_workstation::gem_setup"
include_recipe "pivotal_workstation::mysql"
include_recipe "pivotal_workstation::postgres"
include_recipe "sprout-osx-apps::imagemagick"
include_recipe "sprout-osx-apps::node_js"
include_recipe "pivotal_workstation::qt"
# custom additions from sprout
include_recipe "pivotal_workstation::ec2_api_tools"
include_recipe "pivotal_workstation::locate_on"
include_recipe "sprout-osx-apps::heroku_toolbelt"
include_recipe "sprout-osx-apps::hipchat"
include_recipe "sprout-osx-apps::hub"
include_recipe "sprout-osx-apps::s3cmd"
include_recipe "sprout-osx-apps::tig"
include_recipe "sprout-osx-apps::vlc"
include_recipe "sprout-osx-settings::dock_preferences"
include_recipe "sprout-osx-settings::finder_display_full_path"
# my stuff
include_recipe "miketheman::rescuetime"

include_recipe "miketheman::gitconfig"
include_recipe "miketheman::textual_theme"

include_recipe "miketheman::ssh_keys"
include_recipe "miketheman::my_preferences"
include_recipe "miketheman::prompt"
